# Generated by Django 4.0.4 on 2022-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agencija'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencija',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
