# Generated by Django 4.0.4 on 2022-05-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_agencija_phnumber_agencija_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putovanje',
            name='agencija',
        ),
    ]
