# Generated by Django 4.0.4 on 2022-05-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_putovanje_agencija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencija',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='agencija',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='agencija',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agencija',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='agencija',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='agencija',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='agencija',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='agencija',
            name='phnumber',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='putovanje',
            name='agencija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.agencija'),
        ),
        migrations.AlterField(
            model_name='agencija',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
