# Generated by Django 4.0.4 on 2022-06-02 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_agencija_date_joined_remove_agencija_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorisnikovaPutovanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.agencija')),
                ('korisnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
