# Generated by Django 4.0.4 on 2022-06-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_korisnikovaputovanja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnikovaputovanja',
            name='agencija',
        ),
        migrations.AddField(
            model_name='korisnikovaputovanja',
            name='putovanje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.putovanje'),
        ),
    ]
