# Generated by Django 4.0.4 on 2022-06-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_putovanje_datum_zavrsetka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
